version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_USER: hd_user
      POSTGRES_PASSWORD: secret123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports: ["6379:6379"]

  backend:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - postgres
      - redis
    ports: ["8000:8000"]

  celery:
    build: ./backend
    env_file: ./backend/.env
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - redis
      - backend

  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    depends_on:
      - backend

volumes:
  pgdata:
